# fly.toml file generated for versacebot on 2023-04-18T00:03:42+02:00

app = "versacebot"
primary_region = "jnb"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
